theme: "dot-org-hugo-theme"
title: "K8up - Kubernetes Backup Operator"
timeZone: "Europe/Zurich"

hasCJKLanguage: false
contentDir: content/en/
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

privacy:
  youtube:
    privacyEnhanced: true
  vimeo:
    enableDNT: true
