en:
  languageName: English
  weight: 1
  copyright: "Copyright &copy; K8up Authors {{< current_year >}}. Documentation distributed under [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/) -- Copyright &copy; {{< current_year >}} The Linux Foundation. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage](https://www.linuxfoundation.org/legal/trademark-usage) page. -- [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "K8up - Kubernetes Backup Operator"
  description: "Kubernetes Backup Operator"
  params:
    main_cta:
      text: "Getting Started"
      link: "https://k8up.io/k8up/2.8/tutorials/tutorial.html"
    footer_cta:
      text: "GitHub"
      link: "https://github.com/k8up-io/"
    github_edit: "Edit this page on GitHub"

  menu:
    main:
      - identifier: "docs"
        name: "Documentation"
        url: "https://docs.k8up.io/"
        weight: 1
      - identifier: "community"
        name: "Community"
        weight: 2
      - identifier: "about"
        name: "About"
        url: "/community/"
        weight: 1
        parent: "community"
      - identifier: "contrib"
        name: "Contribution Guide"
        url: "/contrib/"
        weight: 2
        parent: "community"
      - identifier: "coc"
        name: "Code of Conduct"
        url: "/coc/"
        weight: 3
        parent: "community"
      - identifier: "security"
        name: "Vulnerability Reporting"
        url: "/vulnerabilities/"
        weight: 4
        parent: "community"
      - identifier: "visual"
        name: "Visual Design"
        url: "/visual/"
        weight: 5
        parent: "community"
      - identifier: "github"
        name: "GitHub"
        url: "https://github.com/k8up-io/k8up"
        weight: 3
      - identifier: "roadmap"
        name: "Roadmap"
        url: "https://github.com/k8up-io/k8up/milestones"
        weight: 4
