######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "images/k8up-logo.svg"
logo_on_black: "images/k8up-logo-white-text.svg"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/social-share.png"]

github:
  repo_url: "https://github.com/k8up-io/website"
  show_edit_link: true

social_links:
  devstats: "https://k8up.devstats.cncf.io/"
  discord: ""
  facebook: ""
  flickr: ""
  github: "https://github.com/k8up-io/k8up"
  instagram: ""
  landscape: ""
  linkedin: ""
  mastodon: "https://mastodon.vshn.social/@k8up"
  pinterest: ""
  rss: ""
  slack: "https://app.slack.com/client/T08PSQ7BQ/C06GP0D5FEF"
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: false
